replicaCount: 3

image:
  repository: hasindukarunathilaka/user-service  # Your Docker Hub repository name
  tag: "latest"  # The tag for your Docker image
  pullPolicy: Always

service:
  type: LoadBalancer  # Service type for external access
  port: 80  # Port to expose the service

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
